version: "3.7"

networks:
  magento2:
    driver: bridge

services:
  websrv:
    hostname: websrv
    build:
      context: "./bin/${WEBSERVER}"
    container_name: 'websrv'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
      - "222:22"
    links:
      - mysql
      - redis
    networks:
      - magento2
    volumes:
      - type: bind
        source: ./conf/php/php.ini
        target: /usr/local/etc/php/php.ini
      - type: volume
        source: app-data
        target: /app
      - type: volume
        source: app-log
        target: /var/log/apache2
    depends_on:
      - mysql
      - redis

  mysql:
    hostname: dbsrv
    build:
      context: "./bin/${DATABASE}"
    container_name: 'dbsrv'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    networks:
      - magento2
    volumes:
      - type: volume
        source: app-db
        target: /var/lib/mysql
      - type: volume
        source: app-log
        target: /var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    hostname: redis
    container_name: 'redis'
    image: bitnami/redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
    networks:
      - magento2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - type: bind
        source: ./conf/redis/redis.conf
        target: /opt/bitnami/redis/etc/redis.conf
      - type: volume
        source: redis-db
        target: /bitnami/redis/data

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: 'pma'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - magento2

  esearch:
    hostname: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: 'elastic'
    ports:
      - "19200:9200"
      - "19300:9300"
    restart: 'always'
    volumes:
      - type: volume
        source: es-db
        target: /usr/share/elasticsearch/data
    networks:
      - magento2

volumes:
  app-data:
  app-db:
  app-log:
  redis-db:
  es-db:
